version: "3.7"
services:
  fiber-client:
    image: golang:alpine
    networks:
      - example
    command:
      - "/bin/sh"
      - "-c"
      - "wget http://fiber-server:3000/users/123 && cat 123"
    depends_on:
      - fiber-server
  fiber-server:
    build:
      dockerfile: $PWD/Dockerfile
    ports:
      - "3000:80"
    command:
      - "/bin/sh"
      - "-c"
      - "/go/bin/server"
    networks:
      - example
networks:
  example:
