name: Release Drafter (v3 packages)

on:
    push:
        branches:
            - master
            - main

jobs:
    changes:
        runs-on: ubuntu-latest
        permissions:
            pull-requests: read
        outputs:
            packages: ${{ steps.filter.outputs.changes || '[]' }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Generate filters
              id: filter-setup
              shell: bash
              run: |
                  shopt -s nullglob
                  packages=(v3/*/)

                  if (( ${#packages[@]} == 0 )); then
                      echo "filters={}" >> "$GITHUB_OUTPUT"
                      exit 0
                  fi

                  {
                      echo "filters<<EOF"
                      for pkg in "${packages[@]}"; do
                          pkg=${pkg#v3/}
                          pkg=${pkg%/}
                          printf "'%s': 'v3/%s/**'\n" "$pkg" "$pkg"
                      done
                      echo "EOF"
                  } >> "$GITHUB_OUTPUT"

            - name: Filter changes
              id: filter
              uses: dorny/paths-filter@v3
              with:
                  filters: ${{ steps.filter-setup.outputs.filters }}

    release-drafter:
        needs: changes
        runs-on: ubuntu-latest
        timeout-minutes: 30
        if: needs.changes.outputs.packages != '[]'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        strategy:
            matrix:
                package: ${{ fromJSON(needs.changes.outputs.packages || '[]') }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Generate dynamic config from template
              id: generate-config
              run: |
                  package="${{ matrix.package }}"
                  directory="v3/${package}"
                  {
                      echo "config<<EOF"
                      sed -e "s|{{PACKAGE}}|$package|g" -e "s|{{DIRECTORY}}|$directory|g" .github/release-drafter-template.yml
                      echo "EOF"
                  } >> "$GITHUB_OUTPUT"

            - name: Use dynamic release-drafter configuration
              uses: ReneWerner87/release-drafter@6dec4ceb1fb86b6514f11a2e7a39e1dedce709d0
              with:
                  config: ${{ steps.generate-config.outputs.config }}
