name: 'Sync docs'

on:
    push:
        branches:
            - master
            - main
        paths:
            - '**/*.md'
    workflow_dispatch:
        inputs:
            mode:
                description: 'Trigger mode: choose "push" to run the push flow or "release" to run the release flow'
                required: true
                default: 'push'
            tag_name:
                description: 'Tag name to use for release mode (optional when triggering manually)'
                required: false
                default: ''
    release:
        types: [published]
        branches:
            - '*/v[0-9]+.[0-9]+.[0-9]+'

jobs:
    sync-docs:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5
              with:
                  fetch-depth: 2

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: '18'

            - name: Install JQ
              run: sudo apt-get install jq

            - name: Sync docs
              run: ./.github/scripts/sync_docs.sh
              env:
                  # If manually triggered, use the provided inputs; otherwise keep the event-driven values
                  EVENT: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.mode || github.event_name }}
                  TAG_NAME: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag_name || github.ref_name }}
                  TOKEN: ${{ secrets.DOC_SYNC_TOKEN }}
                  SOURCE_DIR: 'v3'
                  DESTINATION_DIR: 'docs/contrib'
