name: "Test Testcontainers Services"

on:
  push:
    branches:
      - master
      - main
    paths:
      - 'testcontainers/**'
  pull_request:
    paths:
      - 'testcontainers/**'

jobs:
  Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - 1.25.x
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v5

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '${{ matrix.go-version }}'

      - name: Run Test
        working-directory: ./testcontainers
        run: go test -v -race ./...
