name: "Test Fgprof"

on:
  push:
    branches:
      - master
      - main
    paths:
      - 'v3/fgprof/**'
  pull_request:
    paths:
      - 'v3/fgprof/**'

jobs:
  Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - 1.25.x
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v5
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '${{ matrix.go-version }}'
      - name: Run Test
        working-directory: ./v3/fgprof
        run: go test -v -race ./...
