name: "Test opa"

on:
  push:
    branches:
      - master
      - main
    paths:
      - 'v3/opa/**/*.go'
      - 'v3/opa/go.mod'
  pull_request:
    paths:
      - 'v3/opa/**/*.go'
      - 'v3/opa/go.mod'

jobs:
  Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - 1.25.x
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v5
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: '${{ matrix.go-version }}'
      - name: Run Test
        working-directory: ./v3/opa
        run: go test -v -race ./...
