name: "Test i18n"

on:
  push:
    branches:
      - master
      - main
    paths:
      - 'v3/i18n/**/*.go'
      - 'v3/i18n/go.mod'
      - 'v3/i18n/go.sum'
  pull_request:
    paths:
      - 'v3/i18n/**/*.go'
      - 'v3/i18n/go.mod'
      - 'v3/i18n/go.sum'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  Tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      GOWORK: off
    strategy:
      matrix:
        go-version:
          - 1.25.x
          - 1.26.x
    steps:
      - name: Fetch Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: '${{ matrix.go-version }}'
          cache-dependency-path: v3/i18n/go.sum
      - name: Run Test
        uses: gofiber/.github/.github/actions/gotestsum@main
        with:
          working-directory: ./v3/i18n
          packages: ./...
          rerun-fails: '2'
          args: -race -count=1
